// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Ch9X81oEufb6iddLpckW66KnhuTyvnU',
    appId: '1:608896769104:web:cbafc1a661351a1da64555',
    messagingSenderId: '608896769104',
    projectId: 'campuseventapp-90446',
    authDomain: 'campuseventapp-90446.firebaseapp.com',
    storageBucket: 'campuseventapp-90446.firebasestorage.app',
    measurementId: 'G-2BDTKK4WRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmE4_DOmz2l9n0pY8LpGXXxU0iTLkFwyQ',
    appId: '1:608896769104:android:e79ed0c636515edca64555',
    messagingSenderId: '608896769104',
    projectId: 'campuseventapp-90446',
    storageBucket: 'campuseventapp-90446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7HyTO08BuP4oKQ-07qSlgzz1aoLYAME',
    appId: '1:608896769104:ios:bce8ce1d6b1f3d52a64555',
    messagingSenderId: '608896769104',
    projectId: 'campuseventapp-90446',
    storageBucket: 'campuseventapp-90446.firebasestorage.app',
    iosClientId: '608896769104-3q1do5877veemlnudf9ksqlvm8v0d6m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEventsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7HyTO08BuP4oKQ-07qSlgzz1aoLYAME',
    appId: '1:608896769104:ios:bce8ce1d6b1f3d52a64555',
    messagingSenderId: '608896769104',
    projectId: 'campuseventapp-90446',
    storageBucket: 'campuseventapp-90446.firebasestorage.app',
    iosClientId: '608896769104-3q1do5877veemlnudf9ksqlvm8v0d6m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.campusEventsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Ch9X81oEufb6iddLpckW66KnhuTyvnU',
    appId: '1:608896769104:web:fb492029d870d0b8a64555',
    messagingSenderId: '608896769104',
    projectId: 'campuseventapp-90446',
    authDomain: 'campuseventapp-90446.firebaseapp.com',
    storageBucket: 'campuseventapp-90446.firebasestorage.app',
    measurementId: 'G-YKMM0M5WEB',
  );
}
